title: imkeshiba
email: imkeshiba@gmail.com
description: >-
  Hey, I'm Keshiba. I'm a Software Engineer.
  Dipping my toes into CTF challenges and InfoSec.
  Welcome to my personal blog. Have fun here.
baseurl: ""
url: "http://keshiba.me"
twitter_username: keshiba
github_username:  keshiba
author:
  name: keshiba
  email: imkeshiba@gmail.com
google_analytics: UA-172880769-1


# Build settings
remote_theme: "keshiba/better-minima@v0.1.2"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

better-minima:
  social_links:
    twitter: imkeshiba
    github: keshiba
